/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "DeployAi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "E2B_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "EXAAI_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Frontend": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "MyApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "MyBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "OpenRouterApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Researcher": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}
