/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ViewLazyImport = createFileRoute('/view')()
const ProfileLazyImport = createFileRoute('/profile')()
const PredictionMarketLazyImport = createFileRoute('/predictionMarket')()
const MarketLazyImport = createFileRoute('/market')()
const BattleBotsLazyImport = createFileRoute('/battleBots')()
const AiAgentCreationLazyImport = createFileRoute('/aiAgentCreation')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ViewLazyRoute = ViewLazyImport.update({
  id: '/view',
  path: '/view',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/view.lazy').then((d) => d.Route))

const ProfileLazyRoute = ProfileLazyImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))

const PredictionMarketLazyRoute = PredictionMarketLazyImport.update({
  id: '/predictionMarket',
  path: '/predictionMarket',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/predictionMarket.lazy').then((d) => d.Route),
)

const MarketLazyRoute = MarketLazyImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/market.lazy').then((d) => d.Route))

const BattleBotsLazyRoute = BattleBotsLazyImport.update({
  id: '/battleBots',
  path: '/battleBots',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/battleBots.lazy').then((d) => d.Route))

const AiAgentCreationLazyRoute = AiAgentCreationLazyImport.update({
  id: '/aiAgentCreation',
  path: '/aiAgentCreation',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/aiAgentCreation.lazy').then((d) => d.Route),
)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/aiAgentCreation': {
      id: '/aiAgentCreation'
      path: '/aiAgentCreation'
      fullPath: '/aiAgentCreation'
      preLoaderRoute: typeof AiAgentCreationLazyImport
      parentRoute: typeof rootRoute
    }
    '/battleBots': {
      id: '/battleBots'
      path: '/battleBots'
      fullPath: '/battleBots'
      preLoaderRoute: typeof BattleBotsLazyImport
      parentRoute: typeof rootRoute
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketLazyImport
      parentRoute: typeof rootRoute
    }
    '/predictionMarket': {
      id: '/predictionMarket'
      path: '/predictionMarket'
      fullPath: '/predictionMarket'
      preLoaderRoute: typeof PredictionMarketLazyImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileLazyImport
      parentRoute: typeof rootRoute
    }
    '/view': {
      id: '/view'
      path: '/view'
      fullPath: '/view'
      preLoaderRoute: typeof ViewLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/aiAgentCreation': typeof AiAgentCreationLazyRoute
  '/battleBots': typeof BattleBotsLazyRoute
  '/market': typeof MarketLazyRoute
  '/predictionMarket': typeof PredictionMarketLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/view': typeof ViewLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/aiAgentCreation': typeof AiAgentCreationLazyRoute
  '/battleBots': typeof BattleBotsLazyRoute
  '/market': typeof MarketLazyRoute
  '/predictionMarket': typeof PredictionMarketLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/view': typeof ViewLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/aiAgentCreation': typeof AiAgentCreationLazyRoute
  '/battleBots': typeof BattleBotsLazyRoute
  '/market': typeof MarketLazyRoute
  '/predictionMarket': typeof PredictionMarketLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/view': typeof ViewLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aiAgentCreation'
    | '/battleBots'
    | '/market'
    | '/predictionMarket'
    | '/profile'
    | '/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aiAgentCreation'
    | '/battleBots'
    | '/market'
    | '/predictionMarket'
    | '/profile'
    | '/view'
  id:
    | '__root__'
    | '/'
    | '/aiAgentCreation'
    | '/battleBots'
    | '/market'
    | '/predictionMarket'
    | '/profile'
    | '/view'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AiAgentCreationLazyRoute: typeof AiAgentCreationLazyRoute
  BattleBotsLazyRoute: typeof BattleBotsLazyRoute
  MarketLazyRoute: typeof MarketLazyRoute
  PredictionMarketLazyRoute: typeof PredictionMarketLazyRoute
  ProfileLazyRoute: typeof ProfileLazyRoute
  ViewLazyRoute: typeof ViewLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AiAgentCreationLazyRoute: AiAgentCreationLazyRoute,
  BattleBotsLazyRoute: BattleBotsLazyRoute,
  MarketLazyRoute: MarketLazyRoute,
  PredictionMarketLazyRoute: PredictionMarketLazyRoute,
  ProfileLazyRoute: ProfileLazyRoute,
  ViewLazyRoute: ViewLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/aiAgentCreation",
        "/battleBots",
        "/market",
        "/predictionMarket",
        "/profile",
        "/view"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/aiAgentCreation": {
      "filePath": "aiAgentCreation.lazy.tsx"
    },
    "/battleBots": {
      "filePath": "battleBots.lazy.tsx"
    },
    "/market": {
      "filePath": "market.lazy.tsx"
    },
    "/predictionMarket": {
      "filePath": "predictionMarket.lazy.tsx"
    },
    "/profile": {
      "filePath": "profile.lazy.tsx"
    },
    "/view": {
      "filePath": "view.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
